### ISSUE TITLE
Magic modifier will not be added (Dämonenschild/demon shield) Magic III

### ISSUE THREAD

**Issue by KorthaseC** [Plushtoast/dsa5-foundryVTT#1235]
**Describe the bug**
When you try to roll the dice for Dämonenschild/demon shield and have the Scholar of Shanada Ben-Oni, it shows in the modifer thats easier but after clicking on roll its not added.

**To Reproduce**
1. Go to 'Magic in an Actor'
2. Click on 'Dämonenschild/demon shield Dice button'
3. Click on 'Roll button'
4. In chat the modifer is 0

**Expected behavior**
The modifier should be 1

**Screenshots**
![image](https://user-images.githubusercontent.com/48507825/197382278-c30f5f2e-c546-4bb1-bb1b-7b851dd985c4.png)
![image](https://user-images.githubusercontent.com/48507825/197382294-ff0bf17f-d421-49bc-a571-9508dd631007.png)

**Versions:**
- Foundry Version 10
- DSA/TDE version 4.1.10
- DSA Aventurian Magic III 4.1.1

**Additional context**

**Comment by Plushtoast** [comment]
I guess this bug has been fixed a long time ago by accident:

![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/d69cd2dd-50e4-43d9-b662-5973607957b6)

Or there might be a misunderstanding.
If it shows up in this box:
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/50e279c8-0d20-4648-be9a-f5cefe958cf8)

It is not selected by default, because many abilities depend on "textual conditions" also. So you have to select it if you think it would affect his spell.
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/7fbbe233-8368-41d6-9d93-363a60d55558)

The background of the line of the ability has to be a dark blue like in the img above.
