### ISSUE TITLE
DSA/TDE considers that you are german speaking if you don't speak english

### ISSUE THREAD

**Issue by Majea** [Plushtoast/dsa5-foundryVTT#1363]
**Describe the bug**

If your Foundry application is setup to run in another language than english and you start a world that is setup to use DSA, then the world forces the whole foundry application to german. This means that the whole application and all other worlds (including non-DSA worlds such as a 5e or pathfinder) are now switched to german. 

**To Reproduce**
1. Set foundry in a language that is not german or english. Example: french. 
2. Create a new world for 5E
3. Create a new world for the DSA system. 
4. start this new DSA world
5. => Foundry swtiches to german
6. Leave the DSA world
7. open the 5E world
8. => Foundry is still in german and the 5E world is in german

**Expected behaviour**

A system should never force anyone to speak a specific language. If your system doesn't support a language, Foundry will automatically take care of falling back to a default language for that system, but the system itself should not change the active language. This impacts everything and not only the system.

**Additional context**

This is related to the following code in `init.js`. This code forces the Foundry application to switch to german when it's not in english (or german, but that has no effect). 

```
if (!["de", "en"].includes(game.i18n.lang)) {
        console.warn(`DSA5 - ${game.i18n.lang} is not a supported language. Falling back to default language.`)
        game.settings.set("core", "language", "de").then(()=> foundry.utils.debouncedReload())
    }
```

Please note that, in plain text, the code above can be read as follows: "If you do not speak english or german, then you must speak german". How does that sound?

---
Side note: I've played Das Schwarze Auge in the early 80's. I really want to get back to that game so I bought the 5th edition and I love it. But I only play on Foundry now. My players don't speak german and few speak english. So the fact that the system is forbidding the usage of other languages, including on elements not related to DSA, is a blocker for game adoption (inside and outside Foundry).

**Comment by mckee14** [comment]
I'm sure Plushtoast can give feedback about the core language switch.

About "you must use english or german", I may bring some light into it.
The complex rules and combinations led to the fact that the code refers to the names of any items, special abilities, advantages etc., basically everything is adressed by its name. Therefore, it's not possible to mix entries from different languages (like importing a DE special ability into an EN world).

These DE/EN mixes led to many errors in the beginning, so they implemented kind of a "choose DE or EN" step. I was not aware that this language selection bleeds out to foundry core setting, which is uncool indeed. Inside the TDA module, it makes sense to streamline and force one language for all players.

I'm not sure if translation into other languages is possible at all, this would be another question to be answered by the devs.

**Comment by Plushtoast** [comment]
Your copied code fragment already shows the answer.
This system only works in de and en. Any other language is not supported.

This is due to technical reasons as Mckee tried to explain (there are some more), also due to licencing issues. But the biggest reason is that 99% of the users are german. There are almost no english players and french players are even less.
We noticed that people struggle with the setup of foundry. E.g. whenever you change the PC or the browser it loses all settings. Also especially beginners are unable to read notifications that they have to set the proper language. They just ignore everything. This leads to people complaining why the system is in english and why this and that problem and so forth. 
So the best way to make this user friendly was to force it to german (because 99%).

Adding other languages is also work and this is already an insane amount of work. 

French is the closest language to being added but the amount of effort is in no relation to the expected amount of french (I assume you r french) people playing this.

So sorry. This solution is very intentional and required for me to have a peaceful evening.

**Comment by mckee14** [comment]
Just an idea. Would it be hard to implement a GM only option which just prevents DSA to change the core language? 
So it must be activated by the GM but it allows to play DSA in either DE or EN, while having your foundry core stay in japanese, french or whatever.

Because despite all the (understandable) reasons for this design, it's usually a no-go to tamper core settings.

**Comment by Majea** [comment]
@Plushtoast 
I find your answer a bit brutal, especially in the beginning. But ok. 
I can understand that you had technical issues that pushed you to make this choice, but your decision doesn't impact just the language you support. It impacts the languages Foundry and the other systems support. You are actually affecting the whole application. 

Your argument about the fact that few people play in French holds, of course. You are automatically switching them to German. So that makes total sense. And yes, people move on when you show a popup message. Even if they can read your message in whatever language you chose to show it, they have no other choice but to move on.

I can understand that setting up Foundry and configuring it can be challenging for some people. But do you really think this is your responsibility, as a system provider, to help people getting their Foundry working in German? This is a problem with Foundry, not with the DSA system. The current solution is inducing side effects on all the non-German (or non-English) users. I like the idea from @mckee14 to have the GM help the users setting up their system instead of forcing it. This is probably something that deserves more thought.

Finally, I don't know what licencing issues you may be facing, but I don't think that forcing a language on the whole Foundry application can enforce any licence in any way. What matters is what you deliver, not what others do with the product. Trying to police what people do on their computer is a slippery slope and I hope you won't go that way.

Anyway, if you happen to change your mind one day, please reach out and I might be able to help, either as a programmer or as a native French speaker. 

Note: I'm actually Belgian, not French, but that shouldn't matter, right?

**Comment by Plushtoast** [comment]
The answer was honest not brutal. But if you prefer a nice answer it is this one: 
The circumstances require a certain amount of pragmatism which we apply whereever it is necessary

**Comment by mckee14** [comment]
Yeah, but imagine it the other way around. I install and play TDE in
german. Then I want to try out DnD, but for some reason it switches my
Foundry to EN.

Now I have problems within TDE because of DnD and thats just not really
nice, is it? :)

Plushtoast ***@***.***> schrieb am Do., 16. Feb. 2023, 02:22:

**Comment by Plushtoast** [comment]
Next patch will show an unclosable popup which shows that the language is about to change instead of an automatic change.
Can#t do without the switching.
