### ISSUE TITLE
Heilkunde Wunden funktioniert nicht

### ISSUE THREAD

**Issue by Schorschus** [Plushtoast/dsa5-foundryVTT#1585]
**Describe the bug**
Wenn ein Held einen anderen per Target mit Heilkunde Wunden versorgen möchte,  wird der daraus entstehende Effekt auf das Ziel nicht umgesetzt.

**To Reproduce**
1. Go to '...' Heilkunde Wunde
2. Click on '....' Effekt (Ziel)

**Expected behavior**
Auswahlfenster mit 1) Linderung 2) Regeneration erscheint

**Screenshots**
Scheinbar ist das Marko "treatWounds" fehlerhaft.

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/2cef71cd-cea0-4586-92a8-39bb1aec6061)

**Versions:**
- Foundry Version 11.315
- DSA/TDE version 5.2.5
- Related modules version

**Additional context**

**Comment by mckee14** [comment]
Das sollte der GM würfeln. Mindestens muss ein GM eingeloggt sein und auf dessen screen wird dann der dialog gerendert.Das geht offenbar nicht anders weil nur GM in andere chars schreiben dürfen.Als ich lokal mir GM und spieler parallell eingeloggt war, hats auch nichr sauber funktioniert wenn der spieler die probe wirft. Nur wenn der GM alles abhandelt hats auch das gemacht, was ich erwartet hatte.Allenfalls könnte man das so ändern, dass spieler A probt und das ergebnis gibt eine chat card, welche spieler B dann auf sich anwenden kann. Sonst fällt mir grad keine verbesserung ein.Gesendet von unterwegsAm 08.12.2023 um 13:48 schrieb Schorschus ***@***.***>:﻿
Describe the bug
Wenn ein Held einen anderen per Target mit Heilkunde Wunden versorgen möchte, dann wird der daraus entstehende Effekt auf das Ziel nicht umgesetzt.
To Reproduce
Steps to reproduce the behavior:

Go to '...' Heilkunde Wunde
Click on '....' Effekt (Ziel)

Expected behavior
Auswahlfenster mit 1) Linderung 2) Regeneration erscheint
Screenshots
Scheinbar ist das Marko "treatWounds" fehlerhaft.
image.png (view on web)
Versions:

Foundry Version 11.315
DSA/TDE version 5.2.5
Related modules version

Additional context
Add any other context about the problem here.

**Comment by Plushtoast** [comment]
Der Screenshot bezieht sich auf irgendeinen Sound.

Ansonsten gilt:
Heilkunde würfeln kann jeder, Effekt übertragen auch

Aber das Popup erscheint beim Spielleiter (wegen Editier Rechten) und er muss das dann richtig clicken.

**Comment by Schorschus** [comment]
Hey zusammen,
sorry, da habe ich den falschen Screenshot gepostet. 
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/8d59f1bc-d3b8-45a4-81f4-8139c1c08f7d)


Ich habe die Heilkunde Wunde-Probe direkt als GM durchgeführt, und leider tut sich dort kein entsprechendes Optionsfeld auf. 
Bei beiden Akteuren habe ich die Talent-Migration im Vorfeld durchgeführt. 

Der aktuelle Versions-Stand sollte auch korrekt sein. 

Danke schon einmal im Voraus

**Comment by Plushtoast** [comment]
Dieser screenshot bezieht sich auf das modul autoanimations und kann normalerweise ignoriert werden

**Comment by Schorschus** [comment]
Mhh - okay danke für die Info. Bei euch scheint es ja zu funktionieren, da muss der Fehler ja dann bei mir / in meiner Welt liegen. 
Ich schau mal, ob ich etwas dazu finde.

Danke für eure Rückmeldung


Update: Last try: Folgenden Error erhalte ich, wenn ich den Effekt aufs Ziel anwende.
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/2354294f-1866-4369-bd69-006b5cbe0fc1)

**Comment by Talaren** [comment]
@Schorschus bekomme den gleichen Fehler egal ob ich als Spieler oder Spielleiter versuche den Effekt anzuwenden.

DSA 5.2.6
Foundry: 11.315

```
ReferenceError: callMacro is not defined
    <anonymous> dsa5.js line 12 > eval:1
    <anonymous> dsa5.js line 12 > eval:1
    applyAdvancedFunction dsa5.js:12
    applyEffect dsa5.js:12
    chatListeners dsa5.js:46
    wrapLock dsa5.js:46
    chatListeners dsa5.js:46
    jQuery 8
    activateListeners foundry.js:85850
    _render foundry.js:5842
    _render foundry.js:69030
    _render foundry.js:85588
    _render foundry.js:70869
    render foundry.js:5769
    initializeUI foundry.js:8869
    setupGame foundry.js:8725
    _initializeGameView foundry.js:9990
    _initializeView foundry.js:9966
    initialize foundry.js:8650
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:805
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:91833
    async* foundry.js:91809
dsa5.js:12:18970

```

Es scheint das der Makroaufruf im Statuseffekt fehlerhaft ist:
callMacro("dsa5.macros", "treatWounds", actor, source, qs, { sourceActor })

**Comment by Schorschus** [comment]
@Talaren Danke für dein Feedback.
@Plushtoast magst du das noch einmal checken?

**Comment by Plushtoast** [comment]
Hab schon einen fix
