### ISSUE TITLE
Bug or feature? Token prototype dimensions & scale are consistently ignored whenever dropping new token onto scene

### ISSUE THREAD

**Issue by coffiarts** [Plushtoast/dsa5-foundryVTT#1605]
**Describe the bug**
Whenever I am dropping actors as new tokens onto a scene, their dimensions (width & height) and scale configured in the actor's prototype settings seem to get ignored. Whatever I preconfigure, it gets reset to default (1) on the new token.
So I have to manually adjust each and every scene token to my needs.

**To Reproduce**
See video below. It demonstrates how I can reproduce this in an **absolutely clean (100% mod free)** tde5 world.

**Expected behavior**
In the case shown in the video, around 00:48, I'd expect the skeleton's scene token to be "3" in widht/height and "1.5" in scale (instead of both being "1").

**Demonstration Video**
https://github.com/Plushtoast/dsa5-foundryVTT/assets/39616483/66ea4abd-c717-4d5d-8fce-c8128d90fbf6

**Versions:**
- Foundry Version: 11.315 (latest)
- DSA/TDE version: 5.2.8 (latest)
- Related modules version (none, no modules involved at all)

[POST EDIT:] What I forgot to mention: The whole thing works absolutely fine in an equivalent (mod-free) **dnd5e** game world. if required, I can provide a video for that as well!

**Comment by Plushtoast** [comment]
This is intentional:

* The size of the token is calculated based on the size category setting in the attributes tab of the sheet (which also affects automatically calculated combat modifiers based on size
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/f97ab6f7-fa8b-486f-b446-1ba8b35f499b)

* You can disable this behaviour by configuring the menu via the button shown in the image below and disabling auto token size (though this menu should probably go to the prototype token settings)
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/dfb7c6e0-19bd-4bc5-964b-f747168ecb44)

**Comment by coffiarts** [comment]
Thanks for that clarification! I must confess that I've been completely unaware of that feature.
It makes a lot of sense (by itself), though at the same time it makes my attempts to manipulate token size by macro or module code quite complex. At least I know now why it has been failing all the time only in tde5 and not in other systems. 
Still I understand that I can only disable this _per actor_ individually, not _globally_, right?

**Comment by Plushtoast** [comment]
jup
