### ISSUE TITLE
The language choosing function force Foundry to this language: no way back !

### ISSUE THREAD

**Issue by vonv** [Plushtoast/dsa5-foundryVTT#1835]
When choosing the language for the compendium to display, it turn all the Foundry into that langage ! Impossible to go back !

I a m french. And it turned all my Foundry to English.
The Foundry option is set to french and i uninstall/install the french core translation module: no effect.

**Versions:**
- Foundry Version 12
- DSA/TDE version latest
- Related modules version French translation module

**Comment by Plushtoast** [comment]
You can always switch back to french in the settings of foundry:

![grafik](https://github.com/user-attachments/assets/c1ce1bd5-9ec0-41a7-b3f7-80a19b4a1ba4)

Except for the dark eye which will only work in german or english.

You can disable the  force language setting in the the dark eye system settings. It will remain french then. But a big chunk of features will just be broken.

**Comment by vonv** [comment]
Yes but i think it's intrusive to modify the language here because it affects all my worlds.
And each time i want to play DAS5, i have to switch back :(

**Comment by Plushtoast** [comment]
Foundry doenst support languages per world and the system does not support any other language.
Especially new users fail on setting the right language. Which happened for DSA all the time resulting in users complaining about a lot of stuff. So we enforce this now which improves the situation for everyone using a supported language.

This is fully intentional. I see no other way.

That is also why the popup is telling what is going to happen.
