### ISSUE TITLE
Statuseffekt-Symbole werden invertiert angezeigt.

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#420]
**Describe the bug**
Wenn man einen Zustand/Status händisch ändert, bleibt das Symbol eingeblendet. Wenn man es dann wieder aktiviert, wird es ausgeblendet.

**To Reproduce**
- Senke die LeP eines SC-Actors auf 4: Handlungsunfähig triggert automatisch korrekt.
- Deaktiviere den Status händisch: Symbol bleibt aktiviert, Effekt wird aufgehoben.
- Aktiviere den Status händisch: Symbol wird deaktiviert, Effekt wird angewendet.

**Screenshots**
<img width="586" alt="Bug" src="https://user-images.githubusercontent.com/41292141/120791825-f687d380-c534-11eb-9de8-da5270e4abd2.PNG">

**Desktop (please complete the following information):**

Foundry: 0.86
Game Systems: 2.0.1
Gods of Aventuria I 1.0.3
Aventurian Magic I 1.0.4
Aventurian Magic II 1.0.1
Core Rules 1.1.2
all others up to date too

**Comment by mckee14** [comment]
Ich kann das Verhalten bestätigen, allerdings würde ich den Zustand auch nicht deaktivieren sondern über Rechtsklick ganz aus dem Char löschen. Dann ist das Problem weg :).

**Comment by mckee14** [comment]
I add this here, as it may be related and solved already.

The shapeshift status is behaving weird, too. I shapeshifted an actor, after removing the status, he transformed back but lost his token image.

Then i tried it again, after transforming back the token image was OK, but the shapeshift status has been applied twice. I was able to delete one of it, the other one resisted and i couldn't delete it.

Deleted the token, pulled it to the scene again, still no deleting possible.

I was able to delete the status directly inside of the character (accessed via the char menu, not via token), then the newly pulled token was OK, too.

It smells like it's related to this issue here. If not, let me know and I create a separate isse for it.
